import random
import csv
#difficult level game
file=open("difficult.csv","a",newline='\n')
write=csv.writer(file)
file1=open("difficult.csv",'r')
read=csv.reader(file1)
sl=[0]
for one in read:
    sl.append(int(one[1]))
hs=max(sl)
def difficult():
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print(" Welcome to Number Game            High Score :: ",hs            )
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print()
    print("=========================")
    print(" LEVEL ::  DIFFICULT             ")
    print("=========================")
    print("""
-->You are asked to enter a number between 0 & 6 and computer will generate one number
      if your number and the number produced by the computer is same then you lost the game.

-->Untill you loose the game, your score will be added in background and displayed when you loose.

-->if you enter numbers 1 or 2 then it will be added directly to your score.

-->if you enter 0 then the number generated by the computer will be added to your score.
""")
    name=input("Enter your name :: ")
    while True:
        total=0
        while True:
            try:
                cg=random.randint(0,2)
                user=int(input("Enter your value :"))
                print()
                if user in range(0,3):
                    print("Computer  : ",cg," User : ",user)
                    print()
                    if user !=cg:
                        total+=user
                    elif user==cg:   
                        print("Your score is : ",total)
                        if total==0:
                            print("duck out-->#no comments simply waste")
                        elif total > hs:
                            print("New high score recorded")
                        break
                else:
                    print("Out of range")
                    continue     
            except ValueError or TypeError:
                print("something went wrong try again")
        print()
        con=str(input("do you want to continue y/n :"))
        if con in "nN":
            print()
            break
        else:
            continue
    write.writerow([name,total])
    file.flush()
